# fly.toml app configuration file generated for bmilcs-mini-message-board on 2023-06-22T15:45:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bmilcs-mini-message-board"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
